{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "dbee8db1",
   "metadata": {},
   "outputs": [],
   "source": [
    "from bs4 import BeautifulSoup\n",
    "import requests\n",
    "import pandas as pd"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a34e967e",
   "metadata": {},
   "source": [
    "# NASA Mars News"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "46ebaadb",
   "metadata": {},
   "outputs": [],
   "source": [
    "# URL of page to be scraped\n",
    "url = 'https://mars.nasa.gov/news/'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "feaaa6cf",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Retrieve page with the requests module\n",
    "response = requests.get(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "0649cdd5",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Create BeautifulSoup object; parse with 'html.parser'\n",
    "soup = BeautifulSoup(response.text, 'html.parser')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "523b722c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<!DOCTYPE html>\n",
      "<html lang=\"en\" xml:lang=\"en\" xmlns=\"http://www.w3.org/1999/xhtml\">\n",
      " <head>\n",
      "  <meta content=\"text/html; charset=utf-8\" http-equiv=\"Content-Type\"/>\n",
      "  <!-- Always force latest IE rendering engine or request Chrome Frame -->\n",
      "  <meta content=\"IE=edge,chrome=1\" http-equiv=\"X-UA-Compatible\"/>\n",
      "  <!-- Responsiveness -->\n",
      "  <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\"/>\n",
      "  <!-- Favicon -->\n",
      "  <link href=\"/apple-touch-icon.png\" rel=\"apple-touch-icon\" sizes=\"180x180\"/>\n",
      "  <link href=\"/favicon-32x32.png\" rel=\"icon\" sizes=\"32x32\" type=\"image/png\"/>\n",
      "  <link href=\"/favicon-16x16.png\" rel=\"icon\" sizes=\"16x16\" type=\"image/png\"/>\n",
      "  <link href=\"/manifest.json\" rel=\"manifest\"/>\n",
      "  <link color=\"#e48b55\" href=\"/safari-pinned-tab.svg\" rel=\"mask-icon\"/>\n",
      "  <meta content=\"#000000\" name=\"theme-color\"/>\n",
      "  <meta content=\"authenticity_token\" name=\"csrf-param\">\n",
      "   <meta content=\"ncMoH5/OQouSjfHggdB80+C0/rwe7unvnuYJqt6VFa6PWYYU/kxWdSpiwmqV4f7h/E86dQYRnc7KbQskCos2fw==\" name=\"csrf-token\">\n",
      "    <title>\n",
      "     News  – NASA’s Mars Exploration Program\n",
      "    </title>\n",
      "    <meta content=\"NASA’s Mars Exploration Program \" property=\"og:site_name\"/>\n",
      "    <meta content=\"mars.nasa.gov\" name=\"author\"/>\n",
      "    <meta content=\"Mars, missions, NASA, rover, Curiosity, Opportunity, InSight, Mars Reconnaissance Orbiter, facts\" name=\"keywords\"/>\n",
      "    <meta content=\"NASA’s real-time portal for Mars exploration, featuring the latest news, images, and discoveries from the Red Planet.\" name=\"description\"/>\n",
      "    <meta content=\"NASA’s real-time portal for Mars exploration, featuring the latest news, images, and discoveries from the Red Planet.\" property=\"og:description\"/>\n",
      "    <meta content=\"News  – NASA’s Mars Exploration Program \" property=\"og:title\"/>\n",
      "    <meta content=\"https://mars.nasa.gov/news\" property=\"og:url\"/>\n",
      "    <meta content=\"article\" property=\"og:type\"/>\n",
      "    <meta content=\"2017-09-22 19:53:22 UTC\" property=\"og:updated_time\"/>\n",
      "    <meta content=\"https://mars.nasa.gov/system/site_config_values/meta_share_images/1_mars-nasa-gov.jpg\" property=\"og:image\"/>\n",
      "    <meta content=\"https://mars.nasa.gov/system/site_config_values/meta_share_images/1_mars-nasa-gov.jpg\" name=\"twitter:image\"/>\n",
      "    <link href=\"https://mars.nasa.gov/system/site_config_values/meta_share_images/1_mars-nasa-gov.jpg\" rel=\"image_src\"/>\n",
      "    <meta content=\"195570401081308\" property=\"fb:app_id\"/>\n",
      "    <link href=\"https://fonts.googleapis.com/css?family=Montserrat:200,300,400,500,600,700|Raleway:300,400\" rel=\"stylesheet\"/>\n",
      "    <link href=\"/assets/public_manifest-5054fd17d8295e62047dc115f4d16c901cad41474c46eeea718e87c80296f2a4.css\" media=\"all\" rel=\"stylesheet\">\n",
      "     <link href=\"/assets/mbcms/vendor/jquery.fancybox3-d5d81bdfc05a59e4ea72bca1d8b7fcc399bd3b61f7c06af95a8a48795df69d7a.css\" media=\"screen\" rel=\"stylesheet\">\n",
      "      <link href=\"/assets/gulp/print-240f8bfaa7f6402dfd6c49ee3c1ffea57a89ddd4c8c90e2f2a5c7d63c5753e32.css\" media=\"print\" rel=\"stylesheet\">\n",
      "       <script src=\"/assets/public_manifest-8c743021f292fa52b2c61c5546e5da613e829bb36e1b27bee8ec48167d77094b.js\">\n",
      "       </script>\n",
      "       <script src=\"/assets/mbcms/vendor/jquery.fancybox3-bd48876205805faa43a79e74b656191a4ad37809923b4f3247b571ba82d4458c.js\">\n",
      "       </script>\n",
      "       <script src=\"/assets/mb_manifest-a0ae601bc18c852649e350709ab440161da58529f782ae84172c21f8ea27b714.js\">\n",
      "       </script>\n",
      "       <!--[if gt IE 8]><!-->\n",
      "       <script src=\"/assets/not_ie8_manifest.js\">\n",
      "       </script>\n",
      "       <!--[if !IE]>-->\n",
      "       <script src=\"/assets/not_ie8_manifest.js\">\n",
      "       </script>\n",
      "       <!--<![endif]-->\n",
      "       <script async=\"async\" src=\"//script.crazyegg.com/pages/scripts/0070/1109.js\" type=\"text/javascript\">\n",
      "       </script>\n",
      "       <!-- /twitter cards -->\n",
      "       <meta content=\"summary_large_image\" name=\"twitter:card\"/>\n",
      "       <meta content=\"News \" name=\"twitter:title\"/>\n",
      "       <meta content=\"NASA’s real-time portal for Mars exploration, featuring the latest news, images, and discoveries from the Red Planet.\" name=\"twitter:description\"/>\n",
      "       <meta content=\"https://mars.nasa.gov/system/site_config_values/meta_share_images/1_mars-nasa-gov.jpg\" name=\"twitter:image\"/>\n",
      "      </link>\n",
      "     </link>\n",
      "    </link>\n",
      "   </meta>\n",
      "  </meta>\n",
      " </head>\n",
      " <body id=\"news\">\n",
      "  <svg display=\"none\" height=\"0\" width=\"0\">\n",
      "   <symbol height=\"30\" id=\"circle_plus\" viewbox=\"0 0 30 30\" width=\"30\">\n",
      "    <g fill-rule=\"evenodd\" transform=\"translate(1 1)\">\n",
      "     <circle cx=\"14\" cy=\"14\" fill=\"#fff\" fill-opacity=\".1\" fill-rule=\"nonzero\" r=\"14\" stroke=\"inherit\" stroke-width=\"1\">\n",
      "     </circle>\n",
      "     <path class=\"the_plus\" d=\"m18.856 12.96v1.738h-4.004v3.938h-1.848v-3.938h-4.004v-1.738h4.004v-3.96h1.848v3.96z\" fill=\"inherit\" stroke-width=\"0\">\n",
      "     </path>\n",
      "    </g>\n",
      "   </symbol>\n",
      "   <symbol height=\"30\" id=\"circle_arrow\" viewbox=\"0 0 30 30\" width=\"30\" xmlns=\"http://www.w3.org/2000/svg\">\n",
      "    <g transform=\"translate(1 1)\">\n",
      "     <circle cx=\"14\" cy=\"14\" fill=\"#fff\" fill-opacity=\".1\" r=\"14\" stroke=\"inherit\" stroke-width=\"1\">\n",
      "     </circle>\n",
      "     <path class=\"the_arrow\" d=\"m8.5 15.00025h7.984l-2.342 2.42c-.189.197-.189.518 0 .715l.684.717c.188.197.494.197.684 0l4.35-4.506c.188-.199.188-.52 0-.717l-4.322-4.48c-.189-.199-.496-.199-.684 0l-.684.716c-.189.197-.189.519 0 .716l2.341 2.419h-8.011c-.276 0-.5.223-.5.5v1c0 .275.224.5.5.5z\" fill=\"inherit\" stroke-width=\"0\">\n",
      "     </path>\n",
      "    </g>\n",
      "   </symbol>\n",
      "   <symbol height=\"30\" id=\"circle_close\" viewbox=\"0 0 30 30\" width=\"30\">\n",
      "    <g fill-rule=\"evenodd\" transform=\"translate(1 1)\">\n",
      "     <circle cx=\"14\" cy=\"14\" fill=\"blue\" fill-opacity=\"1\" fill-rule=\"nonzero\" r=\"14\" stroke=\"inherit\" stroke-width=\"1\">\n",
      "     </circle>\n",
      "     <path class=\"the_plus\" d=\"m18.856 12.96v1.738h-4.004v3.938h-1.848v-3.938h-4.004v-1.738h4.004v-3.96h1.848v3.96z\" fill=\"inherit\" stroke-width=\"0\">\n",
      "     </path>\n",
      "    </g>\n",
      "   </symbol>\n",
      "   <symbol height=\"30\" id=\"circle_close_hover\" viewbox=\"0 0 30 30\" width=\"30\">\n",
      "    <g fill-rule=\"evenodd\" transform=\"translate(1 1)\">\n",
      "     <circle cx=\"14\" cy=\"14\" fill=\"white\" fill-opacity=\"1\" fill-rule=\"nonzero\" r=\"14\" stroke=\"inherit\" stroke-width=\"1\">\n",
      "     </circle>\n",
      "     <path class=\"the_plus\" d=\"m18.856 12.96v1.738h-4.004v3.938h-1.848v-3.938h-4.004v-1.738h4.004v-3.96h1.848v3.96z\" fill=\"inherit\" stroke-width=\"0\">\n",
      "     </path>\n",
      "    </g>\n",
      "   </symbol>\n",
      "   <symbol height=\"6\" id=\"chevron_down\" viewbox=\"0 0 10 6\" width=\"10\" xmlns=\"http://www.w3.org/2000/svg\">\n",
      "    <path d=\"m59 7v2.72727273l5 3.27272727 5-3.27272727v-2.72727273l-5 3.2727273z\" transform=\"translate(-59 -7)\">\n",
      "    </path>\n",
      "   </symbol>\n",
      "   <symbol height=\"16\" id=\"gear\" viewbox=\"0 0 16 16\" width=\"16\" xmlns=\"http://www.w3.org/2000/svg\">\n",
      "    <path d=\"m68 9h-1.09c-.15-.91-.5-1.75-1.021-2.471l.761-.77c.39-.39.39-1.029 0-1.42-.391-.39-1.021-.39-1.41 0l-.771.77c-.719-.519-1.469-.869-2.469-1.019v-1.09c0-.55-.45-1-1-1s-1 .45-1 1v1.09c-1 .15-1.75.5-2.47 1.02l-.77-.77c-.389-.39-1.029-.39-1.42 0-.39.391-.39 1.03 0 1.42l.771.77c-.521.72-.871 1.56-1.021 2.47h-1.09c-.55 0-1 .48-1 1.029 0 .551.45.971 1.12.971h.97c.15.91.5 1.75 1.021 2.471l-.771.769c-.39.39-.39 1.029 0 1.42.391.39 1.021.39 1.41 0l.78-.77c.72.52 1.47.87 2.47 1.02v1.09c0 .55.45 1 1 1s1-.45 1-1v-1.09c1-.15 1.75-.5 2.47-1.02l.771.77c.391.39 1.02.39 1.41 0 .39-.391.39-1.03 0-1.42l-.761-.76c.51-.72.87-1.56 1.02-2.48h1.09c.55 0 1-.45 1-1s-.45-1-1-1zm-7 4c-1.66 0-3-1.35-3-3s1.34-3 3-3c1.65 0 3 1.35 3 3s-1.35 3-3 3z\" fill=\"#a79693\" transform=\"translate(-53 -2)\">\n",
      "    </path>\n",
      "   </symbol>\n",
      "  </svg>\n",
      "  <div data-react-cache-id=\"BrowseHappier-0\" data-react-class=\"BrowseHappier\" data-react-props='{\"gt\":1,\"lt\":11}'>\n",
      "  </div>\n",
      "  <div data-react-cache-id=\"HiPO-0\" data-react-class=\"HiPO\" data-react-props=\"{}\">\n",
      "  </div>\n",
      "  <div id=\"main_container\">\n",
      "   <div id=\"site_body\">\n",
      "    <div class=\"site_header_area\">\n",
      "     <header class=\"site_header\">\n",
      "      <div class=\"brand_area\">\n",
      "       <div class=\"brand1\">\n",
      "        <a class=\"nasa_logo\" href=\"http://www.nasa.gov\" target=\"_blank\" title=\"visit nasa.gov\">\n",
      "         NASA\n",
      "        </a>\n",
      "       </div>\n",
      "       <div class=\"brand2\">\n",
      "        <a class=\"top_logo\" href=\"https://science.nasa.gov/\" target=\"_blank\" title=\"Explore NASA Science\">\n",
      "         NASA Science\n",
      "        </a>\n",
      "        <a class=\"sub_logo\" href=\"/mars-exploration/#\" title=\"Mars\">\n",
      "         Mars Exploration Program\n",
      "        </a>\n",
      "       </div>\n",
      "       <img alt=\"\" class=\"print_only print_logo\" src=\"/assets/logo_mars_trio_black@2x.png\"/>\n",
      "      </div>\n",
      "      <a class=\"visuallyhidden focusable\" href=\"#page\">\n",
      "       Skip Navigation\n",
      "      </a>\n",
      "      <div class=\"right_header_container\">\n",
      "       <a class=\"menu_button\" href=\"javascript:void(0);\" id=\"menu_button\">\n",
      "        <span class=\"menu_icon\">\n",
      "         menu\n",
      "        </span>\n",
      "       </a>\n",
      "       <a class=\"modal_close\" id=\"modal_close\">\n",
      "        <span class=\"modal_close_icon\">\n",
      "        </span>\n",
      "       </a>\n",
      "       <div class=\"nav_area\">\n",
      "        <div id=\"site_nav_container\">\n",
      "         <nav class=\"site_nav\" data-react-cache-id=\"Meganav-0\" data-react-class=\"Meganav\" data-react-props=\"{&quot;nav_items&quot;:[{&quot;name&quot;:&quot;Mars Now&quot;,&quot;style&quot;:&quot;icon&quot;,&quot;li_class&quot;:&quot;nav_icon mars_now&quot;,&quot;target&quot;:&quot;_self&quot;,&quot;link&quot;:&quot;/explore/mars-now&quot;,&quot;svg_icon_id&quot;:&quot;nav_icon&quot;,&quot;id&quot;:261,&quot;features&quot;:[{&quot;title&quot;:&quot;Mars Now&quot;,&quot;body&quot;:&quot;View a 3D visualization of all the missions exploring the Red Planet&quot;,&quot;image_src&quot;:&quot;/system/basic_html_elements/225_mars_now_nav.jpg&quot;,&quot;link&quot;:&quot;/explore/mars-now/&quot;,&quot;target&quot;:&quot;_self&quot;,&quot;categories&quot;:[]}],&quot;title&quot;:&quot;&quot;,&quot;short_description&quot;:&quot;View the current location and spacecraft communications activity of operating landers, rovers and orbiters using the NASA’s Mars Relay Network.&quot;},{&quot;name&quot;:&quot;The Red Planet&quot;,&quot;link&quot;:&quot;/#red_planet&quot;,&quot;target&quot;:&quot;_self&quot;,&quot;sections&quot;:[{&quot;items&quot;:[{&quot;name&quot;:&quot;Dashboard&quot;,&quot;link&quot;:&quot;/#red_planet/0&quot;,&quot;target&quot;:&quot;_self&quot;,&quot;id&quot;:9},{&quot;name&quot;:&quot;Science Goals&quot;,&quot;link&quot;:&quot;/#red_planet/1&quot;,&quot;target&quot;:&quot;_self&quot;,&quot;id&quot;:13},{&quot;name&quot;:&quot;The Planet&quot;,&quot;link&quot;:&quot;/#red_planet/2&quot;,&quot;target&quot;:&quot;_self&quot;,&quot;id&quot;:14},{&quot;name&quot;:&quot;Atmosphere&quot;,&quot;link&quot;:&quot;/#red_planet/3&quot;,&quot;target&quot;:&quot;_self&quot;,&quot;id&quot;:16},{&quot;name&quot;:&quot;Astrobiology&quot;,&quot;link&quot;:&quot;/#red_planet/4&quot;,&quot;target&quot;:&quot;_self&quot;,&quot;id&quot;:17},{&quot;name&quot;:&quot;Past, Present, Future, Timeline&quot;,&quot;link&quot;:&quot;/#red_planet/5&quot;,&quot;target&quot;:&quot;_self&quot;,&quot;id&quot;:18}]}],&quot;id&quot;:3,&quot;meganav_style&quot;:&quot;&quot;,&quot;features&quot;:[],&quot;short_description&quot;:null},{&quot;name&quot;:&quot;The Program&quot;,&quot;link&quot;:&quot;/#mars_exploration_program&quot;,&quot;target&quot;:&quot;_self&quot;,&quot;sections&quot;:[{&quot;items&quot;:[{&quot;name&quot;:&quot;Mission Statement&quot;,&quot;link&quot;:&quot;/#mars_exploration_program/0&quot;,&quot;target&quot;:&quot;_self&quot;,&quot;id&quot;:8},{&quot;name&quot;:&quot;About the Program&quot;,&quot;link&quot;:&quot;/#mars_exploration_program/1&quot;,&quot;target&quot;:&quot;_self&quot;,&quot;id&quot;:42},{&quot;name&quot;:&quot;Organization&quot;,&quot;link&quot;:&quot;/#mars_exploration_program/2&quot;,&quot;target&quot;:&quot;_self&quot;,&quot;id&quot;:43},{&quot;name&quot;:&quot;Why Mars?&quot;,&quot;link&quot;:&quot;/#mars_exploration_program/3&quot;,&quot;target&quot;:&quot;_self&quot;,&quot;id&quot;:51},{&quot;name&quot;:&quot;Research Programs&quot;,&quot;link&quot;:&quot;/#mars_exploration_program/4&quot;,&quot;target&quot;:&quot;_self&quot;,&quot;id&quot;:44},{&quot;name&quot;:&quot;Planetary Resources&quot;,&quot;link&quot;:&quot;/#mars_exploration_program/5&quot;,&quot;target&quot;:&quot;_self&quot;,&quot;id&quot;:52},{&quot;name&quot;:&quot;Technologies&quot;,&quot;link&quot;:&quot;/#mars_exploration_program/6&quot;,&quot;target&quot;:&quot;_self&quot;,&quot;id&quot;:56}]}],&quot;id&quot;:2,&quot;meganav_style&quot;:&quot;&quot;,&quot;features&quot;:[],&quot;short_description&quot;:null},{&quot;name&quot;:&quot;News \\u0026 Events&quot;,&quot;link&quot;:&quot;/#news_and_events&quot;,&quot;target&quot;:&quot;_self&quot;,&quot;sections&quot;:[{&quot;items&quot;:[{&quot;name&quot;:&quot;News&quot;,&quot;link&quot;:&quot;/news&quot;,&quot;target&quot;:&quot;_self&quot;,&quot;id&quot;:92},{&quot;name&quot;:&quot;Events&quot;,&quot;link&quot;:&quot;/events&quot;,&quot;target&quot;:&quot;_self&quot;,&quot;id&quot;:93}]}],&quot;id&quot;:4,&quot;meganav_style&quot;:&quot;&quot;,&quot;features&quot;:[],&quot;short_description&quot;:null},{&quot;name&quot;:&quot;Multimedia&quot;,&quot;link&quot;:&quot;/#multimedia&quot;,&quot;target&quot;:&quot;_self&quot;,&quot;sections&quot;:[{&quot;items&quot;:[{&quot;name&quot;:&quot;Images&quot;,&quot;link&quot;:&quot;/multimedia/images/&quot;,&quot;target&quot;:&quot;_self&quot;,&quot;id&quot;:90},{&quot;name&quot;:&quot;Videos&quot;,&quot;link&quot;:&quot;/multimedia/videos/&quot;,&quot;target&quot;:&quot;_self&quot;,&quot;id&quot;:91},{&quot;name&quot;:&quot;Audio&quot;,&quot;link&quot;:&quot;/mars2020/multimedia/audio/&quot;,&quot;target&quot;:&quot;_self&quot;,&quot;id&quot;:427},{&quot;name&quot;:&quot;More Resources&quot;,&quot;link&quot;:&quot;/multimedia/more-resources/&quot;,&quot;target&quot;:&quot;_self&quot;,&quot;id&quot;:413}]}],&quot;id&quot;:5,&quot;meganav_style&quot;:&quot;&quot;,&quot;features&quot;:[],&quot;short_description&quot;:null},{&quot;name&quot;:&quot;Missions&quot;,&quot;link&quot;:&quot;/#missions_gallery_subnav&quot;,&quot;target&quot;:&quot;_self&quot;,&quot;sections&quot;:[{&quot;items&quot;:[{&quot;name&quot;:&quot;Past&quot;,&quot;link&quot;:&quot;/mars-exploration/missions/?category=167&quot;,&quot;target&quot;:&quot;_self&quot;,&quot;id&quot;:38},{&quot;name&quot;:&quot;Present&quot;,&quot;link&quot;:&quot;/mars-exploration/missions/?category=170&quot;,&quot;target&quot;:&quot;_self&quot;,&quot;id&quot;:59},{&quot;name&quot;:&quot;Future&quot;,&quot;link&quot;:&quot;/mars-exploration/missions/?category=171&quot;,&quot;target&quot;:&quot;_self&quot;,&quot;id&quot;:60},{&quot;name&quot;:&quot;International Partners&quot;,&quot;link&quot;:&quot;/mars-exploration/partners&quot;,&quot;target&quot;:&quot;_self&quot;,&quot;id&quot;:40}]}],&quot;id&quot;:6,&quot;meganav_style&quot;:&quot;&quot;,&quot;features&quot;:[],&quot;short_description&quot;:null},{&quot;name&quot;:&quot;More&quot;,&quot;link&quot;:&quot;/#more&quot;,&quot;target&quot;:&quot;_self&quot;,&quot;sections&quot;:[],&quot;id&quot;:7,&quot;meganav_style&quot;:&quot;&quot;,&quot;features&quot;:[],&quot;short_description&quot;:null}],&quot;gallery_subnav_items&quot;:[{&quot;thumb&quot;:&quot;/system/missions/list_view_images/23_PIA23764-RoverNamePlateonMars-320x240.jpg&quot;,&quot;id&quot;:23,&quot;title&quot;:&quot;Mars 2020 Perseverance Rover&quot;,&quot;description&quot;:&quot;A mission to investigate key questions about potential life on Mars. &quot;,&quot;date&quot;:&quot;July 17, 2020&quot;,&quot;url&quot;:&quot;/mars-exploration/missions/mars2020/&quot;,&quot;link_text&quot;:&quot;&quot;,&quot;target&quot;:&quot;_blank&quot;,&quot;mi_traveled&quot;:null,&quot;gallery_subnav_link&quot;:&quot;https://mars.nasa.gov/mars2020/&quot;},{&quot;thumb&quot;:&quot;/system/missions/list_view_images/2_PIA14175-thmfeat.jpg&quot;,&quot;id&quot;:2,&quot;title&quot;:&quot;Curiosity Rover&quot;,&quot;description&quot;:&quot;The largest and most capable rover ever sent to Mars.&quot;,&quot;date&quot;:&quot;November 26, 2011&quot;,&quot;url&quot;:&quot;/mars-exploration/missions/mars-science-laboratory&quot;,&quot;link_text&quot;:&quot;&quot;,&quot;target&quot;:&quot;_blank&quot;,&quot;mi_traveled&quot;:16.32,&quot;gallery_subnav_link&quot;:&quot;https://mars.nasa.gov/msl/home/&quot;},{&quot;thumb&quot;:&quot;/system/missions/list_view_images/21_PIA22743-320x240.jpg&quot;,&quot;id&quot;:21,&quot;title&quot;:&quot;InSight Lander&quot;,&quot;description&quot;:&quot;A mission to study the deep interior of Mars. &quot;,&quot;date&quot;:&quot;November 26, 2018&quot;,&quot;url&quot;:&quot;/mars-exploration/missions/insight/&quot;,&quot;link_text&quot;:&quot;&quot;,&quot;target&quot;:&quot;_blank&quot;,&quot;mi_traveled&quot;:null,&quot;gallery_subnav_link&quot;:&quot;https://mars.nasa.gov/insight/&quot;},{&quot;thumb&quot;:&quot;/system/missions/list_view_images/6_maven_320x240.jpg&quot;,&quot;id&quot;:6,&quot;title&quot;:&quot;MAVEN&quot;,&quot;description&quot;:&quot;Measures Mars' atmosphere to understand its climate change.&quot;,&quot;date&quot;:&quot;November 18, 2013&quot;,&quot;url&quot;:&quot;/mars-exploration/missions/maven&quot;,&quot;link_text&quot;:&quot;&quot;,&quot;target&quot;:&quot;_blank&quot;,&quot;mi_traveled&quot;:null,&quot;gallery_subnav_link&quot;:&quot;https://mars.nasa.gov/maven/&quot;},{&quot;thumb&quot;:&quot;/system/missions/list_view_images/8_MRO_320x240.jpg&quot;,&quot;id&quot;:8,&quot;title&quot;:&quot;Mars Reconnaissance Orbiter&quot;,&quot;description&quot;:&quot;Takes high-resolution imagery of Martian terrain with extraordinary clarity. &quot;,&quot;date&quot;:&quot;August 12, 2012&quot;,&quot;url&quot;:&quot;/mars-exploration/missions/mars-reconnaissance-orbiter&quot;,&quot;link_text&quot;:&quot;&quot;,&quot;target&quot;:&quot;_blank&quot;,&quot;mi_traveled&quot;:null,&quot;gallery_subnav_link&quot;:&quot;https://mars.nasa.gov/mro/&quot;},{&quot;thumb&quot;:&quot;/system/missions/list_view_images/5_mars_odyssey320x240.jpg&quot;,&quot;id&quot;:5,&quot;title&quot;:&quot;2001 Mars Odyssey&quot;,&quot;description&quot;:&quot;NASA's longest-lasting spacecraft at Mars. &quot;,&quot;date&quot;:&quot;April  7, 2001&quot;,&quot;url&quot;:&quot;/mars-exploration/missions/odyssey&quot;,&quot;link_text&quot;:&quot;&quot;,&quot;target&quot;:&quot;_blank&quot;,&quot;mi_traveled&quot;:null,&quot;gallery_subnav_link&quot;:&quot;https://mars.nasa.gov/odyssey/&quot;}],&quot;search&quot;:true,&quot;search_placeholder&quot;:{&quot;placeholder&quot;:&quot;&quot;},&quot;highlight_current&quot;:{&quot;highlight&quot;:true,&quot;current_id&quot;:83,&quot;parent_ids&quot;:[]},&quot;search_submit&quot;:&quot;/search/&quot;}\">\n",
      "         </nav>\n",
      "        </div>\n",
      "       </div>\n",
      "      </div>\n",
      "     </header>\n",
      "    </div>\n",
      "    <div id=\"sticky_nav_spacer\">\n",
      "    </div>\n",
      "    <div id=\"page\">\n",
      "     <div class=\"page_cover\">\n",
      "     </div>\n",
      "     <!-- title to go in the page_header -->\n",
      "     <div class=\"header_mask\">\n",
      "      <section class=\"content_page module\">\n",
      "      </section>\n",
      "     </div>\n",
      "     <div class=\"grid_list_page module content_page\">\n",
      "      <div class=\"grid_layout\">\n",
      "       <article>\n",
      "        <header id=\"page_header\">\n",
      "        </header>\n",
      "        <div class=\"react_grid_list grid_list_container\" data-react-cache-id=\"GridListPage-0\" data-react-class=\"GridListPage\" data-react-props='{\"left_column\":false,\"class_name\":\"\",\"default_view\":\"list_view\",\"model\":\"news_items\",\"view_toggle\":false,\"search\":\"true\",\"list_item\":\"News\",\"title\":\"News\",\"categories\":[\"19,165,184,204\"],\"order\":\"publish_date desc,created_at desc\",\"no_items_text\":\"There are no items matching these criteria.\",\"site_title\":\"NASA’s Mars Exploration Program \",\"short_title\":\"Mars\",\"site_share_image\":\"/system/site_config_values/meta_share_images/1_mars-nasa-gov.jpg\",\"per_page\":null,\"filters\":\"[ [ \\\"date\\\", [ [ \\\"2021\\\", \\\"2021\\\" ], [ \\\"2020\\\", \\\"2020\\\" ], [ \\\"2019\\\", \\\"2019\\\" ], [ \\\"2018\\\", \\\"2018\\\" ], [ \\\"2017\\\", \\\"2017\\\" ], [ \\\"2016\\\", \\\"2016\\\" ], [ \\\"2015\\\", \\\"2015\\\" ], [ \\\"2014\\\", \\\"2014\\\" ], [ \\\"2013\\\", \\\"2013\\\" ], [ \\\"2012\\\", \\\"2012\\\" ], [ \\\"2011\\\", \\\"2011\\\" ], [ \\\"2010\\\", \\\"2010\\\" ], [ \\\"2009\\\", \\\"2009\\\" ], [ \\\"2008\\\", \\\"2008\\\" ], [ \\\"2007\\\", \\\"2007\\\" ], [ \\\"2006\\\", \\\"2006\\\" ], [ \\\"2005\\\", \\\"2005\\\" ], [ \\\"2004\\\", \\\"2004\\\" ], [ \\\"2003\\\", \\\"2003\\\" ], [ \\\"2002\\\", \\\"2002\\\" ], [ \\\"2001\\\", \\\"2001\\\" ], [ \\\"2000\\\", \\\"2000\\\" ] ], [ \\\"Latest\\\", \\\"\\\" ], false, false ], [ \\\"categories\\\", [ [ \\\"Feature Stories\\\", 165 ], [ \\\"Press Releases\\\", 19 ], [ \\\"Spotlights\\\", 184 ], [ \\\"Status Reports\\\", 204 ] ], [ \\\"All Categories\\\", \\\"\\\" ], false, false ] ]\",\"conditions\":null,\"scope_in_title\":true,\"options\":{\"blank_scope\":\"Latest\"},\"results_in_title\":false}'>\n",
      "        </div>\n",
      "       </article>\n",
      "      </div>\n",
      "     </div>\n",
      "     <section class=\"module suggested_features\">\n",
      "      <div class=\"grid_layout\">\n",
      "       <header>\n",
      "        <h2 class=\"module_title\">\n",
      "         You Might Also Like\n",
      "        </h2>\n",
      "       </header>\n",
      "       <section>\n",
      "        <script>\n",
      "         $(document).ready(function(){\n",
      "    $(\".features\").slick({\n",
      "      dots: false,\n",
      "      infinite: true,\n",
      "      speed: 300,\n",
      "      slide: '.features .slide',\n",
      "      slidesToShow: 3,\n",
      "      slidesToScroll: 3,\n",
      "      lazyLoad: 'ondemand',\n",
      "      centerMode: false,\n",
      "      arrows: true,\n",
      "      appendArrows: '.features .slick-nav',\n",
      "      appendDots: \".features .slick-nav\",\n",
      "      responsive: [{\"breakpoint\":953,\"settings\":{\"slidesToShow\":2,\"slidesToScroll\":2,\"centerMode\":false}},{\"breakpoint\":480,\"settings\":{\"slidesToShow\":1,\"slidesToScroll\":1,\"centerMode\":true,\"arrows\":false,\"centerPadding\":\"25px\"}}]\n",
      "    });\n",
      "  });\n",
      "        </script>\n",
      "        <div class=\"features\">\n",
      "         <div class=\"slide\">\n",
      "          <div class=\"image_and_description_container\">\n",
      "           <a href=\"/news/9092/team-behind-nasas-newest-mars-rover-to-honor-persevering-students/\">\n",
      "            <div class=\"rollover_description\">\n",
      "             <div class=\"rollover_description_inner\">\n",
      "              Middle schoolers who have pushed past obstacles to reach their academic goals will be celebrated by the mission team with a personal message beamed down from NASA’s Perseverance rover.\n",
      "             </div>\n",
      "             <div class=\"overlay_arrow\">\n",
      "              <img alt=\"More\" src=\"/assets/overlay-arrow.png\"/>\n",
      "             </div>\n",
      "            </div>\n",
      "            <img alt=\"Team Behind NASA's Newest Mars Rover to Honor Persevering Students\" class=\"img-lazy\" data-lazy=\"/system/news_items/list_view_images/9092_26391_Youve_Got_Perseverance_MainArt_thumbnail.jpg\" src=\"/assets/loading_320x240.png\"/>\n",
      "           </a>\n",
      "          </div>\n",
      "          <div class=\"content_title\">\n",
      "           <a href=\"/news/9092/team-behind-nasas-newest-mars-rover-to-honor-persevering-students/\">\n",
      "            Team Behind NASA's Newest Mars Rover to Honor Persevering Students\n",
      "           </a>\n",
      "          </div>\n",
      "         </div>\n",
      "         <div class=\"slide\">\n",
      "          <div class=\"image_and_description_container\">\n",
      "           <a href=\"/news/9054/nasas-perseverance-sheds-more-light-on-jezero-craters-watery-past/\">\n",
      "            <div class=\"rollover_description\">\n",
      "             <div class=\"rollover_description_inner\">\n",
      "              Pictures from NASA’s latest six-wheeler on the Red Planet suggest the area’s history experienced significant flooding events.\n",
      "             </div>\n",
      "             <div class=\"overlay_arrow\">\n",
      "              <img alt=\"More\" src=\"/assets/overlay-arrow.png\"/>\n",
      "             </div>\n",
      "            </div>\n",
      "            <img alt=\"NASA's Perseverance Sheds More Light on Jezero Crater's Watery Past\" class=\"img-lazy\" data-lazy=\"/system/news_items/list_view_images/9054_PIA24813_thumbnail.jpg\" src=\"/assets/loading_320x240.png\"/>\n",
      "           </a>\n",
      "          </div>\n",
      "          <div class=\"content_title\">\n",
      "           <a href=\"/news/9054/nasas-perseverance-sheds-more-light-on-jezero-craters-watery-past/\">\n",
      "            NASA's Perseverance Sheds More Light on Jezero Crater's Watery Past\n",
      "           </a>\n",
      "          </div>\n",
      "         </div>\n",
      "         <div class=\"slide\">\n",
      "          <div class=\"image_and_description_container\">\n",
      "           <a href=\"/news/9036/nasas-perseverance-rover-collects-puzzle-pieces-of-mars-history/\">\n",
      "            <div class=\"rollover_description\">\n",
      "             <div class=\"rollover_description_inner\">\n",
      "              The rocks it has analyzed for sample collection are helping the team better understand a past marked by volcanic activity and water.\n",
      "             </div>\n",
      "             <div class=\"overlay_arrow\">\n",
      "              <img alt=\"More\" src=\"/assets/overlay-arrow.png\"/>\n",
      "             </div>\n",
      "            </div>\n",
      "            <img alt=\"NASA's Perseverance Rover Collects Puzzle Pieces of Mars' History\" class=\"img-lazy\" data-lazy=\"/system/news_items/list_view_images/9036_1-PIA24840-320x240.jpg\" src=\"/assets/loading_320x240.png\"/>\n",
      "           </a>\n",
      "          </div>\n",
      "          <div class=\"content_title\">\n",
      "           <a href=\"/news/9036/nasas-perseverance-rover-collects-puzzle-pieces-of-mars-history/\">\n",
      "            NASA's Perseverance Rover Collects Puzzle Pieces of Mars' History\n",
      "           </a>\n",
      "          </div>\n",
      "         </div>\n",
      "         <div class=\"slide\">\n",
      "          <div class=\"image_and_description_container\">\n",
      "           <a href=\"/news/9030/nasa-to-host-briefing-on-successful-sample-collection-of-martian-rock/\">\n",
      "            <div class=\"rollover_description\">\n",
      "             <div class=\"rollover_description_inner\">\n",
      "              Panelists will discuss the Perseverance rover’s successful collection of the sample and latest science analysis.\n",
      "             </div>\n",
      "             <div class=\"overlay_arrow\">\n",
      "              <img alt=\"More\" src=\"/assets/overlay-arrow.png\"/>\n",
      "             </div>\n",
      "            </div>\n",
      "            <img alt=\"NASA to Host Briefing on Successful Sample Collection of Martian Rock\" class=\"img-lazy\" data-lazy=\"/system/news_items/list_view_images/9030_PIA24805-thumb.jpg\" src=\"/assets/loading_320x240.png\"/>\n",
      "           </a>\n",
      "          </div>\n",
      "          <div class=\"content_title\">\n",
      "           <a href=\"/news/9030/nasa-to-host-briefing-on-successful-sample-collection-of-martian-rock/\">\n",
      "            NASA to Host Briefing on Successful Sample Collection of Martian Rock\n",
      "           </a>\n",
      "          </div>\n",
      "         </div>\n",
      "         <div class=\"slide\">\n",
      "          <div class=\"image_and_description_container\">\n",
      "           <a href=\"/news/9007/nasas-perseverance-team-assessing-first-mars-sampling-attempt/\">\n",
      "            <div class=\"rollover_description\">\n",
      "             <div class=\"rollover_description_inner\">\n",
      "              The rover continues to explore Jezero Crater while the team assesses today’s activities.\n",
      "             </div>\n",
      "             <div class=\"overlay_arrow\">\n",
      "              <img alt=\"More\" src=\"/assets/overlay-arrow.png\"/>\n",
      "             </div>\n",
      "            </div>\n",
      "            <img alt=\"NASA's Perseverance Team Assessing First Mars Sampling Attempt\" class=\"img-lazy\" data-lazy=\"/system/news_items/list_view_images/9007_PIA24795_thumbnail.jpg\" src=\"/assets/loading_320x240.png\"/>\n",
      "           </a>\n",
      "          </div>\n",
      "          <div class=\"content_title\">\n",
      "           <a href=\"/news/9007/nasas-perseverance-team-assessing-first-mars-sampling-attempt/\">\n",
      "            NASA's Perseverance Team Assessing First Mars Sampling Attempt\n",
      "           </a>\n",
      "          </div>\n",
      "         </div>\n",
      "         <div class=\"slide\">\n",
      "          <div class=\"image_and_description_container\">\n",
      "           <a href=\"/news/8995/nasa-perseverance-mars-rover-to-acquire-first-sample/\">\n",
      "            <div class=\"rollover_description\">\n",
      "             <div class=\"rollover_description_inner\">\n",
      "              The six-wheeler’s science campaign has laid the groundwork for the mission’s next major milestone.\n",
      "             </div>\n",
      "             <div class=\"overlay_arrow\">\n",
      "              <img alt=\"More\" src=\"/assets/overlay-arrow.png\"/>\n",
      "             </div>\n",
      "            </div>\n",
      "            <img alt=\"NASA Perseverance Mars Rover to Acquire First Sample\" class=\"img-lazy\" data-lazy=\"/system/news_items/list_view_images/8995_PIA24746-320x240.jpg\" src=\"/assets/loading_320x240.png\"/>\n",
      "           </a>\n",
      "          </div>\n",
      "          <div class=\"content_title\">\n",
      "           <a href=\"/news/8995/nasa-perseverance-mars-rover-to-acquire-first-sample/\">\n",
      "            NASA Perseverance Mars Rover to Acquire First Sample\n",
      "           </a>\n",
      "          </div>\n",
      "         </div>\n",
      "         <div class=\"grid_layout\">\n",
      "          <div class=\"slick-nav_container\">\n",
      "           <div class=\"slick-nav\">\n",
      "           </div>\n",
      "          </div>\n",
      "         </div>\n",
      "        </div>\n",
      "       </section>\n",
      "      </div>\n",
      "     </section>\n",
      "    </div>\n",
      "    <footer id=\"site_footer\">\n",
      "     <div class=\"grid_layout\">\n",
      "      <section class=\"upper_footer\">\n",
      "       <div class=\"share_newsletter_container\">\n",
      "        <div class=\"newsletter\">\n",
      "         <h2>\n",
      "          Get the Mars Newsletter\n",
      "         </h2>\n",
      "         <form action=\"/newsletter-subscribe\">\n",
      "          <input id=\"email\" name=\"email\" placeholder=\"enter email address\" type=\"email\" value=\"\"/>\n",
      "          <input data-disable-with=\"\" name=\"commit\" type=\"submit\" value=\"\"/>\n",
      "         </form>\n",
      "        </div>\n",
      "        <div class=\"share\">\n",
      "         <h2>\n",
      "          Follow the Journey\n",
      "         </h2>\n",
      "         <div class=\"social_icons\">\n",
      "          <!-- AddThis Button BEGIN -->\n",
      "          <div class=\"addthis_toolbox addthis_default_style addthis_32x32_style\">\n",
      "           <a addthis:userid=\"MarsCuriosity\" class=\"addthis_button_twitter_follow icon\">\n",
      "            <img alt=\"twitter\" src=\"/assets/twitter_icon@2x.png\"/>\n",
      "           </a>\n",
      "           <a addthis:userid=\"MarsCuriosity\" class=\"addthis_button_facebook_follow icon\">\n",
      "            <img alt=\"facebook\" src=\"/assets/facebook_icon@2x.png\"/>\n",
      "           </a>\n",
      "           <a addthis:userid=\"nasa\" class=\"addthis_button_instagram_follow icon\">\n",
      "            <img alt=\"instagram\" src=\"/assets/instagram_icon@2x.png\"/>\n",
      "           </a>\n",
      "           <a addthis:url=\"https://mars.nasa.gov/rss/api/?feed=news&amp;category=all&amp;feedtype=rss\" class=\"addthis_button_rss_follow icon\">\n",
      "            <img alt=\"rss\" src=\"/assets/rss_icon@2x.png\"/>\n",
      "           </a>\n",
      "          </div>\n",
      "         </div>\n",
      "         <script src=\"//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5a690e4c1320e328\">\n",
      "         </script>\n",
      "        </div>\n",
      "       </div>\n",
      "       <div class=\"gradient_line\">\n",
      "       </div>\n",
      "      </section>\n",
      "      <section class=\"sitemap\">\n",
      "       <div class=\"sitemap_directory\" id=\"sitemap_directory\">\n",
      "        <div class=\"sitemap_block\">\n",
      "         <div class=\"footer_sitemap_item\">\n",
      "          <h3 class=\"sitemap_title\">\n",
      "           <a href=\"/#red_planet\">\n",
      "            The Red Planet\n",
      "           </a>\n",
      "          </h3>\n",
      "          <ul>\n",
      "           <li>\n",
      "            <div class=\"global_subnav_container\">\n",
      "             <ul class=\"subnav\">\n",
      "              <li>\n",
      "               <a href=\"/#red_planet/0\" target=\"_self\">\n",
      "                Dashboard\n",
      "               </a>\n",
      "              </li>\n",
      "              <li>\n",
      "               <a href=\"/#red_planet/1\" target=\"_self\">\n",
      "                Science Goals\n",
      "               </a>\n",
      "              </li>\n",
      "              <li>\n",
      "               <a href=\"/#red_planet/2\" target=\"_self\">\n",
      "                The Planet\n",
      "               </a>\n",
      "              </li>\n",
      "              <li>\n",
      "               <a href=\"/#red_planet/3\" target=\"_self\">\n",
      "                Atmosphere\n",
      "               </a>\n",
      "              </li>\n",
      "              <li>\n",
      "               <a href=\"/#red_planet/4\" target=\"_self\">\n",
      "                Astrobiology\n",
      "               </a>\n",
      "              </li>\n",
      "              <li>\n",
      "               <a href=\"/#red_planet/5\" target=\"_self\">\n",
      "                Past, Present, Future, Timeline\n",
      "               </a>\n",
      "              </li>\n",
      "             </ul>\n",
      "            </div>\n",
      "           </li>\n",
      "          </ul>\n",
      "         </div>\n",
      "        </div>\n",
      "        <div class=\"sitemap_block\">\n",
      "         <div class=\"footer_sitemap_item\">\n",
      "          <h3 class=\"sitemap_title\">\n",
      "           <a href=\"/#mars_exploration_program\">\n",
      "            The Program\n",
      "           </a>\n",
      "          </h3>\n",
      "          <ul>\n",
      "           <li>\n",
      "            <div class=\"global_subnav_container\">\n",
      "             <ul class=\"subnav\">\n",
      "              <li>\n",
      "               <a href=\"/#mars_exploration_program/0\" target=\"_self\">\n",
      "                Mission Statement\n",
      "               </a>\n",
      "              </li>\n",
      "              <li>\n",
      "               <a href=\"/#mars_exploration_program/1\" target=\"_self\">\n",
      "                About the Program\n",
      "               </a>\n",
      "              </li>\n",
      "              <li>\n",
      "               <a href=\"/#mars_exploration_program/2\" target=\"_self\">\n",
      "                Organization\n",
      "               </a>\n",
      "              </li>\n",
      "              <li>\n",
      "               <a href=\"/#mars_exploration_program/3\" target=\"_self\">\n",
      "                Why Mars?\n",
      "               </a>\n",
      "              </li>\n",
      "              <li>\n",
      "               <a href=\"/#mars_exploration_program/4\" target=\"_self\">\n",
      "                Research Programs\n",
      "               </a>\n",
      "              </li>\n",
      "              <li>\n",
      "               <a href=\"/#mars_exploration_program/5\" target=\"_self\">\n",
      "                Planetary Resources\n",
      "               </a>\n",
      "              </li>\n",
      "              <li>\n",
      "               <a href=\"/#mars_exploration_program/6\" target=\"_self\">\n",
      "                Technologies\n",
      "               </a>\n",
      "              </li>\n",
      "             </ul>\n",
      "            </div>\n",
      "           </li>\n",
      "          </ul>\n",
      "         </div>\n",
      "        </div>\n",
      "        <div class=\"sitemap_block\">\n",
      "         <div class=\"footer_sitemap_item\">\n",
      "          <h3 class=\"sitemap_title\">\n",
      "           <a href=\"/#news_and_events\">\n",
      "            News &amp; Events\n",
      "           </a>\n",
      "          </h3>\n",
      "          <ul>\n",
      "           <li>\n",
      "            <div class=\"global_subnav_container\">\n",
      "             <ul class=\"subnav\">\n",
      "              <li class=\"current\">\n",
      "               <a href=\"/news\" target=\"_self\">\n",
      "                News\n",
      "               </a>\n",
      "              </li>\n",
      "              <li>\n",
      "               <a href=\"/events\" target=\"_self\">\n",
      "                Events\n",
      "               </a>\n",
      "              </li>\n",
      "             </ul>\n",
      "            </div>\n",
      "           </li>\n",
      "          </ul>\n",
      "         </div>\n",
      "        </div>\n",
      "        <div class=\"sitemap_block\">\n",
      "         <div class=\"footer_sitemap_item\">\n",
      "          <h3 class=\"sitemap_title\">\n",
      "           <a href=\"/#multimedia\">\n",
      "            Multimedia\n",
      "           </a>\n",
      "          </h3>\n",
      "          <ul>\n",
      "           <li>\n",
      "            <div class=\"global_subnav_container\">\n",
      "             <ul class=\"subnav\">\n",
      "              <li>\n",
      "               <a href=\"/multimedia/images/\" target=\"_self\">\n",
      "                Images\n",
      "               </a>\n",
      "              </li>\n",
      "              <li>\n",
      "               <a href=\"/multimedia/videos/\" target=\"_self\">\n",
      "                Videos\n",
      "               </a>\n",
      "              </li>\n",
      "              <li>\n",
      "               <a href=\"/mars2020/multimedia/audio/\" target=\"_self\">\n",
      "                Audio\n",
      "               </a>\n",
      "              </li>\n",
      "              <li>\n",
      "               <a href=\"/multimedia/more-resources/\" target=\"_self\">\n",
      "                More Resources\n",
      "               </a>\n",
      "              </li>\n",
      "             </ul>\n",
      "            </div>\n",
      "           </li>\n",
      "          </ul>\n",
      "         </div>\n",
      "        </div>\n",
      "        <div class=\"sitemap_block\">\n",
      "         <div class=\"footer_sitemap_item\">\n",
      "          <h3 class=\"sitemap_title\">\n",
      "           <a href=\"/#missions_gallery_subnav\">\n",
      "            Missions\n",
      "           </a>\n",
      "          </h3>\n",
      "          <ul>\n",
      "           <li>\n",
      "            <div class=\"global_subnav_container\">\n",
      "             <ul class=\"subnav\">\n",
      "              <li>\n",
      "               <a href=\"/mars-exploration/missions/?category=167\" target=\"_self\">\n",
      "                Past\n",
      "               </a>\n",
      "              </li>\n",
      "              <li>\n",
      "               <a href=\"/mars-exploration/missions/?category=170\" target=\"_self\">\n",
      "                Present\n",
      "               </a>\n",
      "              </li>\n",
      "              <li>\n",
      "               <a href=\"/mars-exploration/missions/?category=171\" target=\"_self\">\n",
      "                Future\n",
      "               </a>\n",
      "              </li>\n",
      "              <li>\n",
      "               <a href=\"/mars-exploration/partners\" target=\"_self\">\n",
      "                International Partners\n",
      "               </a>\n",
      "              </li>\n",
      "             </ul>\n",
      "            </div>\n",
      "           </li>\n",
      "          </ul>\n",
      "         </div>\n",
      "        </div>\n",
      "        <div class=\"sitemap_block\">\n",
      "         <div class=\"footer_sitemap_item\">\n",
      "          <h3 class=\"sitemap_title\">\n",
      "           <a href=\"/#more\">\n",
      "            More\n",
      "           </a>\n",
      "          </h3>\n",
      "          <ul>\n",
      "           <li>\n",
      "            <div class=\"global_subnav_container\">\n",
      "             <ul class=\"subnav\">\n",
      "             </ul>\n",
      "            </div>\n",
      "           </li>\n",
      "          </ul>\n",
      "         </div>\n",
      "        </div>\n",
      "       </div>\n",
      "       <div class=\"gradient_line\">\n",
      "       </div>\n",
      "      </section>\n",
      "      <section class=\"lower_footer\">\n",
      "       <div class=\"nav_container\">\n",
      "        <nav>\n",
      "         <ul>\n",
      "          <li>\n",
      "           <a href=\"http://science.nasa.gov/\" target=\"_blank\">\n",
      "            NASA Science Mission Directorate\n",
      "           </a>\n",
      "          </li>\n",
      "          <li>\n",
      "           <a href=\"https://www.jpl.nasa.gov/copyrights.php\" target=\"_blank\">\n",
      "            Privacy\n",
      "           </a>\n",
      "          </li>\n",
      "          <li>\n",
      "           <a href=\"http://www.jpl.nasa.gov/imagepolicy/\" target=\"_blank\">\n",
      "            Image Policy\n",
      "           </a>\n",
      "          </li>\n",
      "          <li>\n",
      "           <a href=\"https://mars.nasa.gov/feedback/\" target=\"_self\">\n",
      "            Feedback\n",
      "           </a>\n",
      "          </li>\n",
      "         </ul>\n",
      "        </nav>\n",
      "       </div>\n",
      "       <div class=\"credits\">\n",
      "        <div class=\"footer_brands_top\">\n",
      "         <p>\n",
      "          Managed by the Mars Exploration Program and the Jet Propulsion Laboratory for NASA’s Science Mission Directorate\n",
      "         </p>\n",
      "        </div>\n",
      "        <!-- .footer_brands -->\n",
      "        <!-- %a.jpl{href: \"\", target: \"_blank\"}Institution -->\n",
      "        <!-- -->\n",
      "        <!-- %a.caltech{href: \"\", target: \"_blank\"}Institution -->\n",
      "        <!-- .staff -->\n",
      "        <!-- %p -->\n",
      "        <!-- - get_staff_for_category(get_field_from_admin_config(:web_staff_category_id)) -->\n",
      "        <!-- - @staff.each_with_index do |staff, idx| -->\n",
      "        <!-- - unless staff.is_in_footer == 0 -->\n",
      "        <!-- = staff.title + \": \" -->\n",
      "        <!-- - if staff.contact_link =~ /@/ -->\n",
      "        <!-- = mail_to staff.contact_link, staff.name, :subject => \"[#{@site_title}]\" -->\n",
      "        <!-- - elsif staff.contact_link.present? -->\n",
      "        <!-- = link_to staff.name, staff.contact_link -->\n",
      "        <!-- - else -->\n",
      "        <!-- = staff.name -->\n",
      "        <!-- - unless (idx + 1 == @staff.size) -->\n",
      "        <!-- %br -->\n",
      "       </div>\n",
      "      </section>\n",
      "     </div>\n",
      "    </footer>\n",
      "   </div>\n",
      "  </div>\n",
      "  <script id=\"_fed_an_ua_tag\" src=\"https://dap.digitalgov.gov/Universal-Federated-Analytics-Min.js?agency=NASA&amp;subagency=JPL-Mars-MEPJPL&amp;pua=UA-9453474-9,UA-118212757-11&amp;dclink=true&amp;sp=searchbox&amp;exts=tif,tiff,wav\" type=\"text/javascript\">\n",
      "  </script>\n",
      " </body>\n",
      "</html>\n",
      "\n"
     ]
    }
   ],
   "source": [
    "# Examine the results, then determine element that contains sought info\n",
    "print(soup.prettify())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "33959890",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[<div class=\"slide\">\n",
      "<div class=\"image_and_description_container\">\n",
      "<a href=\"/news/9092/team-behind-nasas-newest-mars-rover-to-honor-persevering-students/\">\n",
      "<div class=\"rollover_description\">\n",
      "<div class=\"rollover_description_inner\">\n",
      "Middle schoolers who have pushed past obstacles to reach their academic goals will be celebrated by the mission team with a personal message beamed down from NASA’s Perseverance rover.\n",
      "</div>\n",
      "<div class=\"overlay_arrow\">\n",
      "<img alt=\"More\" src=\"/assets/overlay-arrow.png\"/>\n",
      "</div>\n",
      "</div>\n",
      "<img alt=\"Team Behind NASA's Newest Mars Rover to Honor Persevering Students\" class=\"img-lazy\" data-lazy=\"/system/news_items/list_view_images/9092_26391_Youve_Got_Perseverance_MainArt_thumbnail.jpg\" src=\"/assets/loading_320x240.png\"/>\n",
      "</a>\n",
      "</div>\n",
      "<div class=\"content_title\">\n",
      "<a href=\"/news/9092/team-behind-nasas-newest-mars-rover-to-honor-persevering-students/\">\n",
      "Team Behind NASA's Newest Mars Rover to Honor Persevering Students\n",
      "</a>\n",
      "</div>\n",
      "</div>, <div class=\"slide\">\n",
      "<div class=\"image_and_description_container\">\n",
      "<a href=\"/news/9054/nasas-perseverance-sheds-more-light-on-jezero-craters-watery-past/\">\n",
      "<div class=\"rollover_description\">\n",
      "<div class=\"rollover_description_inner\">\n",
      "Pictures from NASA’s latest six-wheeler on the Red Planet suggest the area’s history experienced significant flooding events.\n",
      "</div>\n",
      "<div class=\"overlay_arrow\">\n",
      "<img alt=\"More\" src=\"/assets/overlay-arrow.png\"/>\n",
      "</div>\n",
      "</div>\n",
      "<img alt=\"NASA's Perseverance Sheds More Light on Jezero Crater's Watery Past\" class=\"img-lazy\" data-lazy=\"/system/news_items/list_view_images/9054_PIA24813_thumbnail.jpg\" src=\"/assets/loading_320x240.png\"/>\n",
      "</a>\n",
      "</div>\n",
      "<div class=\"content_title\">\n",
      "<a href=\"/news/9054/nasas-perseverance-sheds-more-light-on-jezero-craters-watery-past/\">\n",
      "NASA's Perseverance Sheds More Light on Jezero Crater's Watery Past\n",
      "</a>\n",
      "</div>\n",
      "</div>, <div class=\"slide\">\n",
      "<div class=\"image_and_description_container\">\n",
      "<a href=\"/news/9036/nasas-perseverance-rover-collects-puzzle-pieces-of-mars-history/\">\n",
      "<div class=\"rollover_description\">\n",
      "<div class=\"rollover_description_inner\">\n",
      "The rocks it has analyzed for sample collection are helping the team better understand a past marked by volcanic activity and water.\n",
      "</div>\n",
      "<div class=\"overlay_arrow\">\n",
      "<img alt=\"More\" src=\"/assets/overlay-arrow.png\"/>\n",
      "</div>\n",
      "</div>\n",
      "<img alt=\"NASA's Perseverance Rover Collects Puzzle Pieces of Mars' History\" class=\"img-lazy\" data-lazy=\"/system/news_items/list_view_images/9036_1-PIA24840-320x240.jpg\" src=\"/assets/loading_320x240.png\"/>\n",
      "</a>\n",
      "</div>\n",
      "<div class=\"content_title\">\n",
      "<a href=\"/news/9036/nasas-perseverance-rover-collects-puzzle-pieces-of-mars-history/\">\n",
      "NASA's Perseverance Rover Collects Puzzle Pieces of Mars' History\n",
      "</a>\n",
      "</div>\n",
      "</div>, <div class=\"slide\">\n",
      "<div class=\"image_and_description_container\">\n",
      "<a href=\"/news/9030/nasa-to-host-briefing-on-successful-sample-collection-of-martian-rock/\">\n",
      "<div class=\"rollover_description\">\n",
      "<div class=\"rollover_description_inner\">\n",
      "Panelists will discuss the Perseverance rover’s successful collection of the sample and latest science analysis.\n",
      "</div>\n",
      "<div class=\"overlay_arrow\">\n",
      "<img alt=\"More\" src=\"/assets/overlay-arrow.png\"/>\n",
      "</div>\n",
      "</div>\n",
      "<img alt=\"NASA to Host Briefing on Successful Sample Collection of Martian Rock\" class=\"img-lazy\" data-lazy=\"/system/news_items/list_view_images/9030_PIA24805-thumb.jpg\" src=\"/assets/loading_320x240.png\"/>\n",
      "</a>\n",
      "</div>\n",
      "<div class=\"content_title\">\n",
      "<a href=\"/news/9030/nasa-to-host-briefing-on-successful-sample-collection-of-martian-rock/\">\n",
      "NASA to Host Briefing on Successful Sample Collection of Martian Rock\n",
      "</a>\n",
      "</div>\n",
      "</div>, <div class=\"slide\">\n",
      "<div class=\"image_and_description_container\">\n",
      "<a href=\"/news/9007/nasas-perseverance-team-assessing-first-mars-sampling-attempt/\">\n",
      "<div class=\"rollover_description\">\n",
      "<div class=\"rollover_description_inner\">\n",
      "The rover continues to explore Jezero Crater while the team assesses today’s activities.\n",
      "</div>\n",
      "<div class=\"overlay_arrow\">\n",
      "<img alt=\"More\" src=\"/assets/overlay-arrow.png\"/>\n",
      "</div>\n",
      "</div>\n",
      "<img alt=\"NASA's Perseverance Team Assessing First Mars Sampling Attempt\" class=\"img-lazy\" data-lazy=\"/system/news_items/list_view_images/9007_PIA24795_thumbnail.jpg\" src=\"/assets/loading_320x240.png\"/>\n",
      "</a>\n",
      "</div>\n",
      "<div class=\"content_title\">\n",
      "<a href=\"/news/9007/nasas-perseverance-team-assessing-first-mars-sampling-attempt/\">\n",
      "NASA's Perseverance Team Assessing First Mars Sampling Attempt\n",
      "</a>\n",
      "</div>\n",
      "</div>, <div class=\"slide\">\n",
      "<div class=\"image_and_description_container\">\n",
      "<a href=\"/news/8995/nasa-perseverance-mars-rover-to-acquire-first-sample/\">\n",
      "<div class=\"rollover_description\">\n",
      "<div class=\"rollover_description_inner\">\n",
      "The six-wheeler’s science campaign has laid the groundwork for the mission’s next major milestone.\n",
      "</div>\n",
      "<div class=\"overlay_arrow\">\n",
      "<img alt=\"More\" src=\"/assets/overlay-arrow.png\"/>\n",
      "</div>\n",
      "</div>\n",
      "<img alt=\"NASA Perseverance Mars Rover to Acquire First Sample\" class=\"img-lazy\" data-lazy=\"/system/news_items/list_view_images/8995_PIA24746-320x240.jpg\" src=\"/assets/loading_320x240.png\"/>\n",
      "</a>\n",
      "</div>\n",
      "<div class=\"content_title\">\n",
      "<a href=\"/news/8995/nasa-perseverance-mars-rover-to-acquire-first-sample/\">\n",
      "NASA Perseverance Mars Rover to Acquire First Sample\n",
      "</a>\n",
      "</div>\n",
      "</div>]\n"
     ]
    }
   ],
   "source": [
    "results = soup.find_all('div', class_='slide')\n",
    "print(results)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "cb71facb",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "-----------\n",
      "\n",
      "Team Behind NASA's Newest Mars Rover to Honor Persevering Students\n",
      "\n",
      "\n",
      "Middle schoolers who have pushed past obstacles to reach their academic goals will be celebrated by the mission team with a personal message beamed down from NASA’s Perseverance rover.\n",
      "\n",
      "-----------\n",
      "\n",
      "NASA's Perseverance Sheds More Light on Jezero Crater's Watery Past\n",
      "\n",
      "\n",
      "Pictures from NASA’s latest six-wheeler on the Red Planet suggest the area’s history experienced significant flooding events.\n",
      "\n",
      "-----------\n",
      "\n",
      "NASA's Perseverance Rover Collects Puzzle Pieces of Mars' History\n",
      "\n",
      "\n",
      "The rocks it has analyzed for sample collection are helping the team better understand a past marked by volcanic activity and water.\n",
      "\n",
      "-----------\n",
      "\n",
      "NASA to Host Briefing on Successful Sample Collection of Martian Rock\n",
      "\n",
      "\n",
      "Panelists will discuss the Perseverance rover’s successful collection of the sample and latest science analysis.\n",
      "\n",
      "-----------\n",
      "\n",
      "NASA's Perseverance Team Assessing First Mars Sampling Attempt\n",
      "\n",
      "\n",
      "The rover continues to explore Jezero Crater while the team assesses today’s activities.\n",
      "\n",
      "-----------\n",
      "\n",
      "NASA Perseverance Mars Rover to Acquire First Sample\n",
      "\n",
      "\n",
      "The six-wheeler’s science campaign has laid the groundwork for the mission’s next major milestone.\n",
      "\n"
     ]
    }
   ],
   "source": [
    "for result in results:\n",
    "    \n",
    "    \n",
    "    \n",
    "    \n",
    "    try:\n",
    "        title = result.find('div', 'content_title')\n",
    "        news_title = title.a.text\n",
    "        news = result.find('div', 'rollover_description_inner')\n",
    "        news_p = news.text\n",
    "        \n",
    "        \n",
    "        if(news_title and news_p):\n",
    "            print('-----------')\n",
    "            print(news_title)\n",
    "            print(news_p)\n",
    "            \n",
    "    except AttributeError as e:\n",
    "        print(e)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "13c1f0ea",
   "metadata": {},
   "source": [
    "# JPL Mars Space Images - Featured Image"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "a1c23b8d",
   "metadata": {},
   "outputs": [],
   "source": [
    "from webdriver_manager.chrome import ChromeDriverManager\n",
    "from splinter import Browser\n",
    "import time"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "id": "dd5f6140",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "\n",
      "====== WebDriver manager ======\n",
      "Current google-chrome version is 96.0.4664\n",
      "Get LATEST chromedriver version for 96.0.4664 google-chrome\n",
      "Driver [C:\\Users\\clytn\\.wdm\\drivers\\chromedriver\\win32\\96.0.4664.45\\chromedriver.exe] found in cache\n"
     ]
    }
   ],
   "source": [
    "# Setup splinter\n",
    "executable_path = {'executable_path': ChromeDriverManager().install()}\n",
    "browser = Browser('chrome', **executable_path, headless=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "id": "0ce8868d",
   "metadata": {},
   "outputs": [],
   "source": [
    "mars_url = 'https://spaceimages-mars.com/'\n",
    "browser.visit(mars_url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "id": "b27941e4",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Parse HTML with Beautiful Soup\n",
    "html = browser.html\n",
    "image_soup = BeautifulSoup(html, 'html.parser')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "id": "f37e195b",
   "metadata": {},
   "outputs": [],
   "source": [
    "button = image_soup.find('a', class_=\"showimg fancybox-thumbs\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "id": "304516cc",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<a class=\"showimg fancybox-thumbs\" href=\"image/featured/mars1.jpg\" target=\"_blank\"> <button class=\"btn btn-outline-light\"> FULL IMAGE</button></a>"
      ]
     },
     "execution_count": 30,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "button"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "id": "c2587339",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Parse HTML with Beautiful Soup\n",
    "html = browser.html\n",
    "image_soup = BeautifulSoup(html, 'html.parser')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "id": "ddc29026",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser.find_by_text(' FULL IMAGE').click()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 33,
   "id": "e136db02",
   "metadata": {},
   "outputs": [],
   "source": [
    "# image_url = image_soup.find('img', class_=\"fancybox-image\")\n",
    "image_url = image_soup.find_all('img')[1]\n",
    "image_url_text = (image_url.get(\"src\"))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 34,
   "id": "67b0c2af",
   "metadata": {},
   "outputs": [],
   "source": [
    "featured_image_url = (f'{mars_url}{image_url_text}')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 35,
   "id": "ebec84d8",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "https://spaceimages-mars.com/image/featured/mars1.jpg\n"
     ]
    }
   ],
   "source": [
    "print(featured_image_url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 36,
   "id": "3352978f",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser.quit()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "08e5256b",
   "metadata": {},
   "source": [
    "# Mars Facts"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 37,
   "id": "58635ad3",
   "metadata": {},
   "outputs": [],
   "source": [
    "mars_facts = 'https://galaxyfacts-mars.com/'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 38,
   "id": "f83cf271",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>0</th>\n",
       "      <th>1</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Equatorial Diameter:</td>\n",
       "      <td>6,792 km</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Polar Diameter:</td>\n",
       "      <td>6,752 km</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Mass:</td>\n",
       "      <td>6.39 × 10^23 kg (0.11 Earths)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Moons:</td>\n",
       "      <td>2 ( Phobos &amp; Deimos )</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Orbit Distance:</td>\n",
       "      <td>227,943,824 km (1.38 AU)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>Orbit Period:</td>\n",
       "      <td>687 days (1.9 years)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>Surface Temperature:</td>\n",
       "      <td>-87 to -5 °C</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>First Record:</td>\n",
       "      <td>2nd millennium BC</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>Recorded By:</td>\n",
       "      <td>Egyptian astronomers</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                      0                              1\n",
       "0  Equatorial Diameter:                       6,792 km\n",
       "1       Polar Diameter:                       6,752 km\n",
       "2                 Mass:  6.39 × 10^23 kg (0.11 Earths)\n",
       "3                Moons:          2 ( Phobos & Deimos )\n",
       "4       Orbit Distance:       227,943,824 km (1.38 AU)\n",
       "5         Orbit Period:           687 days (1.9 years)\n",
       "6  Surface Temperature:                   -87 to -5 °C\n",
       "7         First Record:              2nd millennium BC\n",
       "8          Recorded By:           Egyptian astronomers"
      ]
     },
     "execution_count": 38,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "tables = pd.read_html(mars_facts)\n",
    "\n",
    "mars_table = tables[1]\n",
    "mars_table"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 39,
   "id": "a05a01c4",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Description</th>\n",
       "      <th>Value</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Equatorial Diameter:</td>\n",
       "      <td>6,792 km</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Polar Diameter:</td>\n",
       "      <td>6,752 km</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Mass:</td>\n",
       "      <td>6.39 × 10^23 kg (0.11 Earths)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Moons:</td>\n",
       "      <td>2 ( Phobos &amp; Deimos )</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Orbit Distance:</td>\n",
       "      <td>227,943,824 km (1.38 AU)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>Orbit Period:</td>\n",
       "      <td>687 days (1.9 years)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>Surface Temperature:</td>\n",
       "      <td>-87 to -5 °C</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>First Record:</td>\n",
       "      <td>2nd millennium BC</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>Recorded By:</td>\n",
       "      <td>Egyptian astronomers</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "            Description                          Value\n",
       "0  Equatorial Diameter:                       6,792 km\n",
       "1       Polar Diameter:                       6,752 km\n",
       "2                 Mass:  6.39 × 10^23 kg (0.11 Earths)\n",
       "3                Moons:          2 ( Phobos & Deimos )\n",
       "4       Orbit Distance:       227,943,824 km (1.38 AU)\n",
       "5         Orbit Period:           687 days (1.9 years)\n",
       "6  Surface Temperature:                   -87 to -5 °C\n",
       "7         First Record:              2nd millennium BC\n",
       "8          Recorded By:           Egyptian astronomers"
      ]
     },
     "execution_count": 39,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "mars_table.columns = ['Description', 'Value']\n",
    "mars_table"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 40,
   "id": "d3ffd06d",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'<table border=\"1\" class=\"dataframe\">\\n  <thead>\\n    <tr style=\"text-align: right;\">\\n      <th></th>\\n      <th>Description</th>\\n      <th>Value</th>\\n    </tr>\\n  </thead>\\n  <tbody>\\n    <tr>\\n      <th>0</th>\\n      <td>Equatorial Diameter:</td>\\n      <td>6,792 km</td>\\n    </tr>\\n    <tr>\\n      <th>1</th>\\n      <td>Polar Diameter:</td>\\n      <td>6,752 km</td>\\n    </tr>\\n    <tr>\\n      <th>2</th>\\n      <td>Mass:</td>\\n      <td>6.39 × 10^23 kg (0.11 Earths)</td>\\n    </tr>\\n    <tr>\\n      <th>3</th>\\n      <td>Moons:</td>\\n      <td>2 ( Phobos &amp; Deimos )</td>\\n    </tr>\\n    <tr>\\n      <th>4</th>\\n      <td>Orbit Distance:</td>\\n      <td>227,943,824 km (1.38 AU)</td>\\n    </tr>\\n    <tr>\\n      <th>5</th>\\n      <td>Orbit Period:</td>\\n      <td>687 days (1.9 years)</td>\\n    </tr>\\n    <tr>\\n      <th>6</th>\\n      <td>Surface Temperature:</td>\\n      <td>-87 to -5 °C</td>\\n    </tr>\\n    <tr>\\n      <th>7</th>\\n      <td>First Record:</td>\\n      <td>2nd millennium BC</td>\\n    </tr>\\n    <tr>\\n      <th>8</th>\\n      <td>Recorded By:</td>\\n      <td>Egyptian astronomers</td>\\n    </tr>\\n  </tbody>\\n</table>'"
      ]
     },
     "execution_count": 40,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "mars_html_table = mars_table.to_html()\n",
    "mars_html_table"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 41,
   "id": "404b1393",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'<table border=\"1\" class=\"dataframe\">  <thead>    <tr style=\"text-align: right;\">      <th></th>      <th>Description</th>      <th>Value</th>    </tr>  </thead>  <tbody>    <tr>      <th>0</th>      <td>Equatorial Diameter:</td>      <td>6,792 km</td>    </tr>    <tr>      <th>1</th>      <td>Polar Diameter:</td>      <td>6,752 km</td>    </tr>    <tr>      <th>2</th>      <td>Mass:</td>      <td>6.39 × 10^23 kg (0.11 Earths)</td>    </tr>    <tr>      <th>3</th>      <td>Moons:</td>      <td>2 ( Phobos &amp; Deimos )</td>    </tr>    <tr>      <th>4</th>      <td>Orbit Distance:</td>      <td>227,943,824 km (1.38 AU)</td>    </tr>    <tr>      <th>5</th>      <td>Orbit Period:</td>      <td>687 days (1.9 years)</td>    </tr>    <tr>      <th>6</th>      <td>Surface Temperature:</td>      <td>-87 to -5 °C</td>    </tr>    <tr>      <th>7</th>      <td>First Record:</td>      <td>2nd millennium BC</td>    </tr>    <tr>      <th>8</th>      <td>Recorded By:</td>      <td>Egyptian astronomers</td>    </tr>  </tbody></table>'"
      ]
     },
     "execution_count": 41,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "mars_html_table.replace('\\n', '')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 42,
   "id": "bc41036b",
   "metadata": {},
   "outputs": [],
   "source": [
    "mars_table.to_html('mars_html_table.html')"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "84c9a6be",
   "metadata": {},
   "source": [
    "# Mars Hemispheres"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 43,
   "id": "13546ece",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "\n",
      "====== WebDriver manager ======\n",
      "Current google-chrome version is 96.0.4664\n",
      "Get LATEST chromedriver version for 96.0.4664 google-chrome\n",
      "Driver [C:\\Users\\clytn\\.wdm\\drivers\\chromedriver\\win32\\96.0.4664.45\\chromedriver.exe] found in cache\n"
     ]
    }
   ],
   "source": [
    "# Setup splinter\n",
    "executable_path = {'executable_path': ChromeDriverManager().install()}\n",
    "browser = Browser('chrome', **executable_path, headless=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 44,
   "id": "e516c4ae",
   "metadata": {},
   "outputs": [],
   "source": [
    "hemispheres_url = \"https://marshemispheres.com/\"\n",
    "browser.visit(hemispheres_url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 45,
   "id": "667c2b8b",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[<div class=\"item\">\n",
       " <a class=\"itemLink product-item\" href=\"cerberus.html\"><img alt=\"Cerberus Hemisphere Enhanced thumbnail\" class=\"thumb\" src=\"images/39d3266553462198bd2fbc4d18fbed17_cerberus_enhanced.tif_thumb.png\"/></a>\n",
       " <div class=\"description\">\n",
       " <a class=\"itemLink product-item\" href=\"cerberus.html\">\n",
       " <h3>Cerberus Hemisphere Enhanced</h3>\n",
       " </a>\n",
       " <span class=\"subtitle\" style=\"float:left\">image/tiff 21 MB</span><span class=\"pubDate\" style=\"float:right\"></span><br/>\n",
       " <p>Mosaic of the Cerberus hemisphere of Mars projected into point perspective, a view similar to that which one would see from a spacecraft. This mosaic is composed of 104 Viking Orbiter images acquired…</p>\n",
       " </div>\n",
       " <!-- end description -->\n",
       " </div>,\n",
       " <div class=\"item\">\n",
       " <a class=\"itemLink product-item\" href=\"schiaparelli.html\"><img alt=\"Schiaparelli Hemisphere Enhanced thumbnail\" class=\"thumb\" src=\"images/08eac6e22c07fb1fe72223a79252de20_schiaparelli_enhanced.tif_thumb.png\"/></a>\n",
       " <div class=\"description\">\n",
       " <a class=\"itemLink product-item\" href=\"schiaparelli.html\">\n",
       " <h3>Schiaparelli Hemisphere Enhanced</h3>\n",
       " </a>\n",
       " <span class=\"subtitle\" style=\"float:left\">image/tiff 35 MB</span><span class=\"pubDate\" style=\"float:right\"></span><br/>\n",
       " <p>Mosaic of the Schiaparelli hemisphere of Mars projected into point perspective, a view similar to that which one would see from a spacecraft. The images were acquired in 1980 during early northern…</p>\n",
       " </div>\n",
       " <!-- end description -->\n",
       " </div>,\n",
       " <div class=\"item\">\n",
       " <a class=\"itemLink product-item\" href=\"syrtis.html\"><img alt=\"Syrtis Major Hemisphere Enhanced thumbnail\" class=\"thumb\" src=\"images/55a0a1e2796313fdeafb17c35925e8ac_syrtis_major_enhanced.tif_thumb.png\"/></a>\n",
       " <div class=\"description\">\n",
       " <a class=\"itemLink product-item\" href=\"syrtis.html\">\n",
       " <h3>Syrtis Major Hemisphere Enhanced</h3>\n",
       " </a>\n",
       " <span class=\"subtitle\" style=\"float:left\">image/tiff 25 MB</span><span class=\"pubDate\" style=\"float:right\"></span><br/>\n",
       " <p>Mosaic of the Syrtis Major hemisphere of Mars projected into point perspective, a view similar to that which one would see from a spacecraft. This mosaic is composed of about 100 red and violet…</p>\n",
       " </div>\n",
       " <!-- end description -->\n",
       " </div>,\n",
       " <div class=\"item\">\n",
       " <a class=\"itemLink product-item\" href=\"valles.html\"><img alt=\"Valles Marineris Hemisphere Enhanced thumbnail\" class=\"thumb\" src=\"images/4e59980c1c57f89c680c0e1ccabbeff1_valles_marineris_enhanced.tif_thumb.png\"/></a>\n",
       " <div class=\"description\">\n",
       " <a class=\"itemLink product-item\" href=\"valles.html\">\n",
       " <h3>Valles Marineris Hemisphere Enhanced</h3>\n",
       " </a>\n",
       " <span class=\"subtitle\" style=\"float:left\">image/tiff 27 MB</span><span class=\"pubDate\" style=\"float:right\"></span><br/>\n",
       " <p>Mosaic of the Valles Marineris hemisphere of Mars projected into point perspective, a view similar to that which one would see from a spacecraft. The distance is 2500 kilometers from the surface of…</p>\n",
       " </div>\n",
       " <!-- end description -->\n",
       " </div>]"
      ]
     },
     "execution_count": 45,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "html_hemispheres = browser.html\n",
    "\n",
    "soup_hem = BeautifulSoup(html_hemispheres, 'html.parser')\n",
    "\n",
    "description = soup_hem.find_all('div', class_='item')\n",
    "\n",
    "description"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 46,
   "id": "06e9adc7",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[{'title': 'Cerberus Hemisphere Enhanced',\n",
       "  'img_url': 'images/f5e372a36edfa389625da6d0cc25d905_cerberus_enhanced.tif_full.jpg'},\n",
       " {'title': 'Schiaparelli Hemisphere Enhanced',\n",
       "  'img_url': 'images/3778f7b43bbbc89d6e3cfabb3613ba93_schiaparelli_enhanced.tif_full.jpg'},\n",
       " {'title': 'Syrtis Major Hemisphere Enhanced',\n",
       "  'img_url': 'images/555e6403a6ddd7ba16ddb0e471cadcf7_syrtis_major_enhanced.tif_full.jpg'},\n",
       " {'title': 'Valles Marineris Hemisphere Enhanced',\n",
       "  'img_url': 'images/b3c7c6c9138f57b4756be9b9c43e3a48_valles_marineris_enhanced.tif_full.jpg'}]"
      ]
     },
     "execution_count": 46,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "hemisphere_image_data = []\n",
    "\n",
    "for hemisphere in range(len(description)):\n",
    "\n",
    "    hem_link = browser.find_by_css(\"a.product-item h3\")\n",
    "    hem_link[hemisphere].click()\n",
    "    time.sleep(1)\n",
    "    \n",
    "    img_detail_html = browser.html\n",
    "    imagesoup = BeautifulSoup(img_detail_html, 'html.parser')\n",
    "    \n",
    "    base_url = {'hemispheres_url'}\n",
    "    \n",
    "    hem_url = imagesoup.find('img', class_=\"wide-image\")['src']\n",
    "    \n",
    "    img_url = (base_url and hem_url)\n",
    "\n",
    "    img_title = browser.find_by_css('.title').text\n",
    "    \n",
    "    hemisphere_image_data.append({\"title\": img_title,\n",
    "                              \"img_url\": img_url})\n",
    "    \n",
    "    browser.back()\n",
    "      \n",
    "browser.quit()\n",
    "\n",
    "hemisphere_image_data"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "b76e3447",
   "metadata": {},
   "source": [
    "Items from each step: \n",
    "news_title\n",
    "news_p\n",
    "\n",
    "featured_image_url\n",
    "\n",
    "mars_html_table\n",
    "\n",
    "hemisphere_image_data"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
